-- 코드를 입력하세요
/* SELECT ANIMAL_ID, NAME FROM ANIMAL_INS where NAME LIKE "%EL" and ANIMAL_TYPE = "Dog" */
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS 
where NAME LIKE "%EL%" AND ANIMAL_TYPE = "Dog"
ORDER BY NAME ASC