# SELECT
#     COUNT(SUBSTR(TIME, 6, 7), '0', '') AS FISH_COUNT
#     REPLACE(SUBSTR(TIME, 6, 7), '0', '') AS MONTH
# FROM
#     FISH_INFO
# GROUP BY
#     ID

SELECT
    COUNT(*) AS FISH_COUNT,
    MONTH(TIME) AS MONTH
FROM
    FISH_INFO
GROUP BY
    MONTH
ORDER BY
    MONTH ASC