# SELECT * FROM USED_GOODS_BOARD, USED_GOODS_REPLY
# SELECT * FROM USED_GOODS_BOARD
SELECT 
    B.TITLE, 
    B.BOARD_ID, 
    R.REPLY_ID, 
    R.WRITER_ID, 
    R.CONTENTS, 
    SUBSTR(R.CREATED_DATE, 1, 10) 
FROM 
    USED_GOODS_BOARD AS B, USED_GOODS_REPLY AS R
WHERE 
    B.BOARD_ID = R.BOARD_ID AND B.CREATED_DATE LIKE '2022-10%'
ORDER BY R.CREATED_DATE ASC, B.TITLE ASC